                                                  ML LAB ASSIGNMENT 
                                             SUBMITTED BY:-Abhayjeet(102303761)

Q1:: Questions on Basic NumPy Array 


In [1]:
# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
import numpy as np
arr=np.array([3,4,5,67,8])
reversed=np.flip(arr)
print (reversed)

[ 8 67  5  4  3]


In [2]:
# (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
# NumPy in-built methods 

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array2= array1.flatten() 
print(array2)

[1 2 3 2 4 5 1 2 3]


In [3]:
#(c) Compare the following numpy arrays: 

arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
np.array_equal(arr1,arr2)

True

In [4]:
#(d) Find the most frequent value and their indice(s) in the following arrays: 

x = np.array([1,2,3,4,5,1,2,1,1,1])  

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("Most frequent value IN X ARRAY:", most_frequent)
print("Indices:", indices)


Most frequent value IN X ARRAY: 1
Indices: [0 5 7 8 9]


In [5]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most frequent value IN Y ARRAY:", most_frequent)
print("Indices:", indices)


Most frequent value IN Y ARRAY: 1
Indices: [0 1 2]


In [6]:
#(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
#i. Sum of all elements 
#ii. Sum of all elements row-wise
#iii. Sum of all elements column-wise

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements:", gfg.sum())
print("Row-wise sum:", gfg.sum(axis=1))
print("Column-wise sum:", gfg.sum(axis=0))



Sum of all elements: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [7]:
# (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
# i. Sum of diagonal elements
# ii. Eigen values of matrix
# iii. Eigen vectors of matrix
# iv. Inverse of matrix
# v. Determinant of matrix
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Sum of diagonal elements:", np.trace(n_array))
eigenvalues = np.linalg.eigvals(n_array)
print("Eigenvalues:", eigenvalues)
_, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors:\n", eigenvectors)
inverse = np.linalg.inv(n_array)
print("Inverse of matrix:\n", inverse)
determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)



Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [8]:
#(g) Multiply the following matrices and also find covariance between matrices using NumPy: 

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])


product1 = np.dot(p1, q1)
print("Matrix multiplication result:\n", product1)

cov1 = np.cov(p1.T, q1.T)
print("Covariance between matrices:\n", cov1)


Matrix multiplication result:
 [[16 19]
 [26 31]]
Covariance between matrices:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


In [9]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

q2_T = q2.T  

combined = np.hstack((p2, q2_T))  

cov_matrix = np.cov(combined.T)

print("Covariance between matrices:\n", cov_matrix)


Covariance between matrices:
 [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [10]:
#h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
#find inner, outer and cartesian product?

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
print("Inner product:\n", inner)
outer = np.outer(x, y)
print("Outer product:\n", outer)
from itertools import product

cartesian = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian product:\n", cartesian)





Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

In [11]:
# (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
# i. Find element-wise absolute value
# ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
# row.
# iii. Mean, Median and Standard Deviation of flattened array, of each column, and
# each row 




array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Absolute values
abs_array = np.abs(array)

# ii. Percentiles (Flattened)
p25_flat = np.percentile(array, 25)
p50_flat = np.percentile(array, 50)
p75_flat = np.percentile(array, 75)

# ii. Percentiles (Column-wise)
p25_col = np.percentile(array, 25, axis=0)
p50_col = np.percentile(array, 50, axis=0)
p75_col = np.percentile(array, 75, axis=0)

# ii. Percentiles (Row-wise)
p25_row = np.percentile(array, 25, axis=1)
p50_row = np.percentile(array, 50, axis=1)
p75_row = np.percentile(array, 75, axis=1)

# iii. Mean, Median, Std Dev
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

# Output
print("Absolute values:\n", abs_array)
print("\nFlattened percentiles: 25th =", p25_flat, ", 50th =", p50_flat, ", 75th =", p75_flat)
print("Column-wise percentiles:\n25th =", p25_col, "\n50th =", p50_col, "\n75th =", p75_col)
print("Row-wise percentiles:\n25th =", p25_row, "\n50th =", p50_row, "\n75th =", p75_row)
print("\nFlattened -> Mean:", mean_flat, ", Median:", median_flat, ", Std Dev:", std_flat)
print("Column-wise -> Mean:", mean_col, ", Median:", median_col, ", Std Dev:", std_col)
print("Row-wise -> Mean:", mean_row, ", Median:", median_row, ", Std Dev:", std_row)




Absolute values:
 [[1 2 3]
 [4 5 6]]

Flattened percentiles: 25th = -3.5 , 50th = -0.5 , 75th = 2.5
Column-wise percentiles:
25th = [-2.75 -0.25 -3.75] 
50th = [-1.5  1.5 -1.5] 
75th = [-0.25  3.25  0.75]
Row-wise percentiles:
25th = [-0.5 -5. ] 
50th = [ 1. -4.] 
75th = [2.  0.5]

Flattened -> Mean: -0.5 , Median: -0.5 , Std Dev: 3.8622100754188224
Column-wise -> Mean: [-1.5  1.5 -1.5] , Median: [-1.5  1.5 -1.5] , Std Dev: [2.5 3.5 4.5]
Row-wise -> Mean: [ 0.66666667 -1.66666667] , Median: [ 1. -4.] , Std Dev: [2.05480467 4.78423336]


In [12]:

# (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
# and truncated value, rounded values
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floored = np.floor(a)
ceiled = np.ceil(a)
truncated = np.trunc(a)
rounded = np.round(a)

print("Original array:     ", a)
print("Floor values:       ", floored)
print("Ceil values:        ", ceiled)
print("Truncated values:   ", truncated)
print("Rounded values:     ", rounded)


Original array:      [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values:        [-2. -2. -1.  0.  1.  1.  3.]
Ceil values:         [-1. -1. -0.  1.  2.  2.  3.]
Truncated values:    [-1. -1. -0.  0.  1.  1.  3.]
Rounded values:      [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

In [13]:
#(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
four_smallest = np.sort(array)[:4]

# iv. 5 largest elements
five_largest = np.sort(array)[-5:]

print("Original array:", array)
print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", four_smallest)
print("5 largest elements:", five_largest)



Original array: [ 10  52  62  16  16  54 453]
Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [14]:
#(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only (check if value is an integer using np.floor or .is_integer())
int_elements = array[np.equal(np.mod(array, 1), 0)]

# ii. Float elements only (non-integers)
float_elements = array[np.not_equal(np.mod(array, 1), 0)]

print("Original array:", array)
print("Integer elements only:", int_elements)
print("Float elements only:", float_elements)


Original array: [1.  1.2 2.2 2.  3.  2. ]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [16]:

from PIL import Image
import os

def img_to_array(path):
    img = Image.open(path)

    if img.mode == 'L':  # Grayscale image
        img_array = np.array(img)
        np.savetxt("grayscale_image.txt", img_array, fmt='%d')
        print("Grayscale image saved as grayscale_image.txt")
    elif img.mode == 'RGB':  # RGB image
        img_array = np.array(img)
        # Save each channel separately
        for i, channel in enumerate(['R', 'G', 'B']):
            np.savetxt(f"rgb_{channel}.txt", img_array[:, :, i], fmt='%d')
        print("RGB image channels saved as rgb_R.txt, rgb_G.txt, rgb_B.txt")
    else:
        print("Unsupported image mode:", img.mode)

    return img_array

image_path = r"C:\Users\abhay\OneDrive\Desktop\JN\1_ML_LAB_102303761\stockvault-autumn-leaves186269.jpg"
img_array = img_to_array(image_path)

RGB image channels saved as rgb_R.txt, rgb_G.txt, rgb_B.txt


In [17]:
#Q4 (b): Load the saved text file into Jupyter Notebook


# Check which saved text files exist and load accordingly
if os.path.exists("grayscale_image.txt"):
    # It's a grayscale image
    gray_img = np.loadtxt("grayscale_image.txt", dtype=np.uint8)
    print("Grayscale image loaded:\n", gray_img)

elif all(os.path.exists(f"rgb_{ch}.txt") for ch in ['R', 'G', 'B']):
    # It's an RGB image
    r = np.loadtxt("rgb_R.txt", dtype=np.uint8)
    g = np.loadtxt("rgb_G.txt", dtype=np.uint8)
    b = np.loadtxt("rgb_B.txt", dtype=np.uint8)

    rgb_image = np.stack((r, g, b), axis=2)
    print("RGB image reconstructed:\n", rgb_image)

else:
    print(" No saved image text files found in the current directory.")



RGB image reconstructed:
 [[[175  91  89]
  [177  94  90]
  [177  92  87]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[171  90  87]
  [172  91  88]
  [174  91  87]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[168  93  88]
  [168  90  86]
  [168  87  86]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[141  61  54]
  [145  68  58]
  [169 100  85]
  ...
  [ 58  63  83]
  [ 58  63  83]
  [ 58  63  83]]

 [[162  81  78]
  [149  72  66]
  [153  83  73]
  ...
  [ 56  63  81]
  [ 56  63  82]
  [ 56  63  82]]

 [[157  78  73]
  [139  62  56]
  [142  72  64]
  ...
  [ 53  62  79]
  [ 53  62  79]
  [ 54  63  80]]]


In [18]:
img = Image.fromarray(rgb_image)
img.save("reconstructed_rgb_image.png")
print("Saved as reconstructed_rgb_image.png")

Saved as reconstructed_rgb_image.png
